

export const GET_CHOCOLATES = "GET_CHOCOLATES";
export const GET_CHOCOLATES_SUCCESS = "GET_CHOCOLATES_SUCCESS";
export const GET_CHOCOLATES_FAILURE = "GET_CHOCOLATES_FAILUREs";

//brand Types

export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";


export const GET_CHOCOLATES_BY_ID = "GET_CHOCOLATES_BY_ID";
export const GET_CHOCOLATES_BY_ID_SUCCESS = "GET_CHOCOLATES_BY_ID_SUCCESS";
export const GET_CHOCOLATES_BY_ID_FAILURE = "GET_CHOCOLATES_BY_ID_FAILURE";

export const GET_BRANDS_BY_ID = "GET_BRANDS_BY_ID";
export const GET_BRANDS_BY_ID_SUCCESS = "GET_BRANDS_BY_ID_SUCCESS";
export const GET_BRANDS_BY_ID_FAILURE = "GET_BRANDS_BY_ID_FAILURE";

export const SEARCH_CHOCOLATE = "SEARCH_CHOCOLATE";
export const SEARCH_CHOCOLATE_SUCCESS = "SEARCH_CHOCOLATE_SUCCESS";
export const SEARCH_CHOCOLATE_FAILURE = "SEARCH_CHOCOLATE_SUCCESS";

export const CHANGE_INPUT = "CHANGE_INPUT"